#!/bin/bash

set -euo pipefail

SINK="lexicon.tsv"

download() {
  curl -O http://www.openslr.org/resources/34/santiago.tar.gz
  tar -xzf santiago.tar.gz
  rm santiago.tar.gz
  echo "Downloading..."
}

prepare() {
  local -r WORDS=$(mktemp -t words.XXXXX.$$.txt)
  cut -f1 santiago.txt > "${WORDS}"
  local -r SCRIPT=$(mktemp -t script.XXXXX.$$.sed)
  cat <<EOF > "${SCRIPT}"
# Respell the affricate.
s!ʧ!tʃ!g
# Respells [e].
s!ɛ!e!g
# Respells [g].
s!g!ɡ!g
# Respell the rhotics (using "R" as a temporary).
s!ɾ!R!g 
s!r!ɾ!g
s!R!r!g
# Removes spaces.
s! !!g
EOF
  local -r PRONS=$(mktemp -t prons.XXXXX.$$.txt)
  cut -f2 santiago.txt | 
      sed -f "${SCRIPT}" > "${PRONS}"
  paste "${WORDS}" "${PRONS}" > "${SINK}"
  rm santiago.txt "${WORDS}" "${PRONS}" "${SCRIPT}"
  echo "Preparing lexicon file..."
}

main() {
  download
  prepare
}

main
