#!/bin/bash
# This script, for each TSV file,
# * sorts and removes duplicates, and
# * calls `generalized_split`.

set -eou pipefail

for TSV in ../tsv/*.tsv; do
    # Explicitly uses byte-wise comparison for sorting
    # rather than a locale-dependent comparison.
    LC_ALL=C sort -u -o "${TSV}" "${TSV}"
    ./generalized_split.py "${TSV}"
done
