#!/bin/bash
set -eou pipefail

split() {
    for TSV in ../tsv/*.tsv; do
        # Explicitly uses byte-wise comparison for sorting
        # rather than a locale-dependent comparison.
        LC_ALL=C sort -u -o "${TSV}" "${TSV}"
        ./generalized_split.py "${TSV}"
    done
}

main() {
    time split
    time whitelist
}

main
