#!/bin/bash
# Applies sorting and splitting on all files.

set -eou pipefail

main() {
  ./languages_update.py
    for TSV in ../tsv/*.tsv; do
        # Explicitly uses byte-wise comparison for sorting
        # rather than a locale-dependent comparison.
        LC_ALL=C sort -u -o "${TSV}" "${TSV}"
        ./split.py "${TSV}"
    done
}

main

