#!/bin/bash
# Script for downloading all languages en masse.
#
# This does not exhaust the set of covered languages, merely those we have tried
# thus far.
#
# It seems that the MediaWiki backend may drop queries if too many are made at
# once; therefore we have to run this in serial.

set -eou pipefail

# TODO: Increment this from time to time.
readonly CUTOFFDATE="2019-08-01"

# Add these in alphabetic order with respect to their ISO 639-2 or 639-3 codes.

echo "Bulgarian..."
time wikipron bul \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=bul.tsv

echo "German..."
time wikipron deu \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=deu.tsv

echo "Greek..."
time wikipron ell \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=ell.tsv

echo "English (US)..."
time wikipron eng \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --dialect="US | General American" \
    --cut-off-date="${CUTOFFDATE}" \
    --output=eng.tsv

echo "Spanish (Latin America)..."
time wikipron spa \
    --casefold \
    --no-stress \
    --dialect="Latin America" \
    --cut-off-date="${CUTOFFDATE}" \
    --output=spa.tsv

echo "French (European)..."
time wikipron fra \
    --casefold \
    --no-syllable-boundaries \
    --dialect=European \
    --cut-off-date="${CUTOFFDATE}" \
    --output=fra.tsv

echo "Hindi..."
time wikipron hin \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=hin.tsv
    
echo "Hungarian..."
time wikipron hun \
    --phonetic \
    --casefold \
    --no-stress \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=hun.tsv

echo "Korean..."
time wikipron kor \
    --phonetic \
    --no-syllable-boundaries \
    --cut-off-date="${CUTOFFDATE}" \
    --output=kor.tsv
